org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Windows 上如遇 SSL 证书错误，取消下面两行注释
# systemProp.javax.net.ssl.trustStoreType=WINDOWS-ROOT
# org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8 -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT

# 如果用了本地代理（VPN/科学上网，如 Clash/V2Ray），取消下方注释并改端口
# systemProp.http.proxyHost=127.0.0.1
# systemProp.http.proxyPort=7890
# systemProp.https.proxyHost=127.0.0.1
# systemProp.https.proxyPort=7890
